affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 11
grid_eps: 0.02
grid_range:
- -16.431676725154983
- 16.431676725154983
k: 3
mult_arity: 2
round: 1
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - '0'
- - '0'
- - '0'
- - '0'
symbolic.funs_name.1:
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.2:
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
- - '0'
  - '0'
  - '0'
  - '0'
symbolic.funs_name.3:
- - '0'
  - '0'
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 1
  - 0
- - 4
  - 0
- - 4
  - 0
- - 4
  - 0
- - 1
  - 0
